#define WIFI_SSID "Kimchi and Chips 2.4GHz"
#define WIFI_PASSWORD "coffeekitchen405"
#define MUSCLE_MEMORY_SERVER_HOST "172.30.1.58"
#define MUSCLE_MEMORY_SERVER_PORT 8000
#define MUSCLE_MEMORY_SERVER_PORT_STRING "8000"