#include <driver/gpio.h>

// SPI
#define MM_CONFIG_SPI_PIN_MOSI GPIO_NUM_23
#define MM_CONFIG_SPI_PIN_MISO GPIO_NUM_19
#define MM_CONFIG_SPI_PIN_CLK GPIO_NUM_18
#define MM_CONFIG_SPI_HOST VSPI_HOST
#define MM_CONFIG_SPI_SPEED SPI_MASTER_FREQ_16M

// I2C
#define MM_CONFIG_I2C_PIN_SCL GPIO_NUM_15
#define MM_CONFIG_I2C_PIN_SDA GPIO_NUM_4

// AS5047
#define MM_CONFIG_AS5047_CS GPIO_NUM_5

// DIAL
#define MM_CONFIG_DIAL_PIN_A GPIO_NUM_34
#define MM_CONFIG_DIAL_PIN_B GPIO_NUM_35
#define MM_CONFIG_DIAL_PIN_BUTTON GPIO_NUM_39

// MOTOR DRIVER
#define MM_CONFIG_MOTOR_DRIVER_PIN_A_POSITIVE GPIO_NUM_32
#define MM_CONFIG_MOTOR_DRIVER_PIN_B_POSITIVE GPIO_NUM_14
#define MM_CONFIG_MOTOR_DRIVER_PIN_A_NEGATIVE GPIO_NUM_33
#define MM_CONFIG_MOTOR_DRIVER_PIN_B_NEGATIVE GPIO_NUM_27
#define MM_CONFIG_MOTOR_DRIVER_DAC_A DAC_A
#define MM_CONFIG_MOTOR_DRIVER_DAC_B DAC_B

// SERIAL
#define MM_CONFIG_SERIAL_PIN_TX GPIO_NUM_1
#define MM_CONFIG_SERIAL_PIN_RX GPIO_NUM_2

// OLED
#define MM_CONFIG_OLED_RESET_ENABLED
#define MM_CONFIG_OLED_PIN_RESET GPIO_NUM_16

// CAN
#define MM_CONFIG_CAN_PIN_TX GPIO_NUM_21
#define MM_CONFIG_CAN_PIN_RX GPIO_NUM_22

// MULTITURN
#define MM_CONFIG_MULTITURN_PARTITION_ENABLE

// CURRENT SENSOR
#define MM_CONFIG_CURRENT_SENSOR_INA237