#include <driver/gpio.h>

// SPI
#define MM_CONFIG_SPI_PIN_MOSI GPIO_NUM_23
#define MM_CONFIG_SPI_PIN_MISO GPIO_NUM_19
#define MM_CONFIG_SPI_PIN_CLK GPIO_NUM_18
#define MM_CONFIG_SPI_HOST VSPI_HOST
#define MM_CONFIG_SPI_SPEED SPI_MASTER_FREQ_16M

// I2C
#define MM_CONFIG_I2C_PIN_SCL GPIO_NUM_15
#define MM_CONFIG_I2C_PIN_SDA GPIO_NUM_4

// AS5047
#define MM_CONFIG_AS5047_CS GPIO_NUM_5

// DIAL
#define MM_CONFIG_DIAL_PIN_A GPIO_NUM_36
#define MM_CONFIG_DIAL_PIN_B GPIO_NUM_39
#define MM_CONFIG_DIAL_PIN_BUTTON GPIO_NUM_0

// MOTOR DRIVER
#define MM_CONFIG_MOTOR_DRIVER_PIN_A_POSITIVE GPIO_NUM_13
#define MM_CONFIG_MOTOR_DRIVER_PIN_A_NEGATIVE GPIO_NUM_12
#define MM_CONFIG_MOTOR_DRIVER_PIN_B_POSITIVE GPIO_NUM_14
#define MM_CONFIG_MOTOR_DRIVER_PIN_B_NEGATIVE GPIO_NUM_27
#define MM_CONFIG_MOTOR_DRIVER_DAC_A DAC_A
#define MM_CONFIG_MOTOR_DRIVER_DAC_B DAC_B
#define MM_CONFIG_MOTOR_DRIVER_ENABLE_ENABLED
#define MM_CONFIG_MOTOR_DRIVER_PIN_ENABLE GPIO_NUM_2

// SERIAL
#define MM_CONFIG_SERIAL_PIN_TX GPIO_NUM_1
#define MM_CONFIG_SERIAL_PIN_RX GPIO_NUM_2

// OLED

// CAN
#define MM_CONFIG_CAN_PIN_TX GPIO_NUM_21
#define MM_CONFIG_CAN_PIN_RX GPIO_NUM_22

// CURRENT SENSOR
#define MM_CONFIG_CURRENT_SENSOR_INA237